# base docker-compose file
services:
  ecommerce:
    image: ecommerce # specify the name of the image
    env_file:
      - ./.env
    restart: always

  nginx:
    container_name: my-nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    depends_on:
      - ecommerce
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Mount the nginx.conf file to the container
