# base docker-compose file
services:
  car-parts:
    image: baraajr11/car-parts-app # specify the name of the image
    env_file:
      - ./.env
    environment:
      - DATABASE_LOCAL=${DATABASE_LOCAL}
      - DATABASE_SERVICE=${DATABASE_SERVICE}
      - DATABASE_ATLAS=${DATABASE_ATLAS}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - mongodb
    restart: always

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db # Mount the mongo-data directory to the container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
    depends_on:
      - car-parts
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Mount the nginx.conf file to the container

volumes:
  mongo-data:
    driver: local
