# base docker-compose file
services:
  car-parts:
    image: ecommerce # specify the name of the image
    env_file:
      - ./.env
    depends_on:
      - redis
    restart: always

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    depends_on:
      - car-parts
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Mount the nginx.conf file to the container
