name: Build and Deploy Node App

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build --target production -t ${{ secrets.DOCKER_USERNAME }}/car-parts-app:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/car-parts-app:latest

  # ===============================
  # 🚀 EC2 Deployment (via SSH)
  # ===============================
  deploy-ec2:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Pull the latest image
            docker pull ${{ secrets.DOCKER_USERNAME }}/car-parts-app:latest

            # Stop and remove all containers for this project (based on the compose file)
            docker compose -f docker-compose.yml down

            # Recreate everything
            docker compose -f docker-compose.yml up -d --scale car-parts=2  # adjust scale as needed
